services:
  postgres:
    image: postgres:16-alpine
    platform: linux/arm64      # ← adiciona isso
    environment:
      POSTGRES_DB: tenora_dev
      POSTGRES_USER: tenora_app
      POSTGRES_PASSWORD: tenora123
    ports: ["5432:5432"]
    volumes: ["pgdata:/var/lib/postgresql/data"]

  redis:
    image: redis:7-alpine
    ports: ["6379:6379"]

  bullboard:          # dashboard visual das filas BullMQ
    image: deadly0/bull-board
    platform: linux/amd64      # ← bull-board só tem amd64, usa emulação
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    ports: ["3002:3000"]
    depends_on: [redis]

volumes:
  pgdata: